### ISSUE TITLE
Can I send signal from Neovim to trigger action in Zig?

### ISSUE THREAD

**Issue by ziontee113** [jinzhongjia/znvim#11]
Hello, and thank you very much for creating this library.

I'm trying to create an application that can interact with a live Neovim instance (via unix pipe) both ways back and forth.
I saw in your test file that connecting and sending commands to a live Neovim instance via unix pipe from Zig is possible.

However, I wonder if it's possible to, let's say, I press a keymap in Neovim, and my application in Zig receives that signal, and shows up.

Is this possible? Thank you very much!

**Comment by jinzhongjia** [comment]
In theory, this is possible, but you probably need to use Lua as the callback of the key mapping to pass the message to Zig

**Comment by jinzhongjia** [comment]
Can you explain in detail your specific demand scenario?

**Comment by ziontee113** [comment]
Thank you for responding. Let's imagine this scenario:

1. I open a Neovim session with a named pipe: `nvim --listen ./nvim.pipe`
2. I press a keymap in Neovim, let's say `<C-S-o>`.
3. My already running Zig application receives the signal and connect to that particular Neovim instance.

I could maybe implement a simple REST API in Zig to listen to calls from Neovim. But I'm wondering if there's a more efficient way to achieve the same thing.
Thank you very much.

**Comment by jinzhongjia** [comment]
If you just start a zig instance to connect to neovim, most current solutions start external programs as sub-processes, and use the stdio of the sub-process for communication.

**Comment by ziontee113** [comment]
I used to do the same thing when I was working with Go.
I would set up a REST API, and Neovim just use curl to send JSON payload to the REST end point.

**Comment by jinzhongjia** [comment]
For example, coc.nvim, it starts a child process to communicate with it

**Comment by jinzhongjia** [comment]
This can effectively divide some tasks into additional processes. Exposing additional unixsockets or sockets and named pipes to the outside world, which is not safe in my opinion.

**Comment by jinzhongjia** [comment]
In short, all kinds of neovim remote clients need to connect to neovim through stdio or named pipe or socket.

**Comment by ziontee113** [comment]
> For example, coc.nvim, it starts a child process to communicate with it

Thank you. I'm still very confused of how it works but I'll look into it :+1:

**Comment by jinzhongjia** [comment]
The channels supported by neovim include socket, named pipe, or stdio (start a child process and directly use the stdio of the child process to communicate with it)
The communication protocol can optionally use the msgpackrpc protocol.

**Comment by jinzhongjia** [comment]
https://neovim.io/doc/user/api.html#rpc-connecting
https://neovim.io/doc/user/channel.html#channel-intro

**Comment by ziontee113** [comment]
Would that work if the user start `nvim` regularly in a terminal or in `tmux`? :thinking:

**Comment by ziontee113** [comment]
Since in this case the terminal / tmux spawns the `nvim` process, not our Zig program.

**Comment by jinzhongjia** [comment]
Of course it can run normally, you just need to let neovim's configuration file actively start a jobstart.

**Comment by jinzhongjia** [comment]
Of course, maintaining an additional restapi as you mentioned before is also a solution.

**Comment by jinzhongjia** [comment]
When started as a child process, the zig instance will be in the same life cycle as neovim

**Comment by ziontee113** [comment]
> When started as a child process, the zig instance will be in the same life cycle as neovim

Ah... so something like `coc.nvim` was started as child process, from Neovim, via `jobstart`.
However, I'm trying to connect to a Zig daemon that's already running :thinking:, kinda like Emacs.
So.... I think the REST API might be the way to go.. Since spawning a big heavy GUI program every time Neovim is opened seems undesirable.

**Comment by ziontee113** [comment]
However, security is a concern, since I'd have to expose a named pipe / port :thinking:

**Comment by jinzhongjia** [comment]
If this is the case, then using restapi is indeed the best solution

**Comment by ziontee113** [comment]
Thank you so much for all the answers. :pray: 
I'll go with the restapi solution.
