### ISSUE TITLE
Feature proposal: userdata in method callbacks

### ISSUE THREAD

**Issue by rockorager** [jinzhongjia/znvim#4]
Wondering what you think of change the function signatures of `ReqMethodType` and `NotifyMethodType` from:

```zig
pub const ReqMethodType = *const fn (params: Payload, allocator: Allocator) ResultType;
pub const NotifyMethodType = *const fn (params: Payload, allocator: Allocator) void;
```

to:
```zig
pub const ReqMethodType = struct {
    userdata: ?*anyopaque = null,
    fn: *const fn (params: Payload, allocator: Allocator, userdata: ?*anyopaque) ResultType,
};
pub const NotifyMethodType = struct {
    userdata: ?*anyopaque = null,
    fn: *const fn (params: Payload, allocator: Allocator, userdata: ?*anyopaque) void,
};
```

This would allow embedders to pass along arbitrary userdata through each callback, preventing the need for global variables.

I can send in a PR if you are ok with this change.

**Comment by jinzhongjia** [comment]
A very good suggestion. I have thought about carrying the payload before, but I didn’t think of a good solution. This is great. Welcome to PR.

**Comment by jinzhongjia** [comment]
By the way, I'm trying to update to multi-threading support, but the development hasn't been completed yet.
